### ISSUE TITLE
posts to page

### ISSUE THREAD

**Issue by darren3** [idewz/facefeed#1]
Hello, I have just discovered facefeed as I was looking for an alternative now facebook have depreciated public rss feeds. Would it be possible to remove items from Posts to Page showing in the feeds? Can generate a lot of noise on some pages. Thanks for a great service.

**Comment by siwadon** [comment]
@darren3 Hi, I'm not sure how you  are using it. For me, I use it together with [IFTTT](https://ifttt.com), so I don't have to filter it myself.

**Comment by darren3** [comment]
I was hoping to be able to get RSS feeds of posts from various Public Facebook pages but I think the Posts to Page items showing up means this won't fit my needs. I can't see any way I can filter them using IFTTT or Feed Rinse.

**Comment by siwadon** [comment]
OK, I understand what you mean. I think I can add an option to show only post from page since Facebook Graph API has already supported that.

**Comment by darren3** [comment]
That would be great, thanks. :)

**Comment by darren3** [comment]
Hi idewz, thanks for adding the post types. Its great.
